# -*- coding: utf-8 -*-
"""Évfolyam-oldalak tartalma: matek (1–8.) és helyesírás (1–6.)."""

MATH = {
1: dict(
    intro="Az első osztályban a gyerekek a számok világával ismerkednek: megtanulnak 20-ig számolni, összeadni és kivonni, és az első síkidomokkal is találkoznak. Ebben a korban a rövid, játékos gyakorlás működik a legjobban, ezért az itt található feladatok kis lépésekben nehezednek, és minden kör csak tíz kérdésből áll.",
    learn=["számok olvasása, írása és összehasonlítása a 20-as számkörben (a <, > és = jelekkel)",
           "összeadás és kivonás 20-ig, később tízesátlépéssel",
           "számszomszédok, számsorozatok folytatása, hiányzó szám keresése",
           "a forint érméi és az egyszerű vásárlás",
           "az óra: egész órák leolvasása",
           "alapvető síkidomok felismerése: négyzet, téglalap, háromszög, kör"],
    tips="Elsősnek napi 5–10 perc bőven elég. Érdemes valódi tárgyakkal is számolni (gombok, kockák, érmék), és a képernyős gyakorlást ezzel váltogatni. Ha a gyerek elakad, ne mondd meg a választ, inkább kérdezd meg, hogyan számolná ki. A gyakorló minden rossz válasz után megmutatja a helyes választ és rövid magyarázatot ad hozzá.",
    faq=[("Meddig kell az elsősnek számolnia?", "A tantervek az első évfolyamon általában a 20-as számkört várják el összeadással és kivonással, az év végén esetleg a tízesátlépéssel. Az iskolák és a tankönyvek között lehet eltérés, ezért a tanító tájékoztatása az irányadó."),
         ("Mennyit gyakoroljon egy elsős naponta?", "Általában 5–10 perc elég. A rövid, de rendszeres gyakorlás többet ér, mint a hosszú, ritka."),]),
2: dict(
    intro="A második osztályban a számkör 100-ra bővül, és megjelenik a szorzás és az osztás is. A gyerekek megtanulják a szorzótábla első részét, mértékegységekkel dolgoznak, és az órát fél és negyed óra pontossággal olvassák. Az itt található gyakorlók az év egész anyagát lefedik, a legkönnyebb szinttől a nehezebbig.",
    learn=["számok 100-ig, összeadás és kivonás tízesátlépéssel",
           "a szorzás és az osztás bevezetése, a 2-es, 5-ös és 10-es szorzótábla",
           "páros és páratlan számok, kerekítés tízesre",
           "hosszúság-, tömeg- és űrmértékek: m, cm, dm, kg, dkg, l, dl",
           "az idő: egész, fél és negyed órák, a hét napjai, a hónapok",
           "pénz: forintérmék összeadása, visszajáró"],
    tips="Másodikban a szorzótábla az első nagy feladat. Ne egyszerre próbáljátok megtanulni: a 2-es, 5-ös és 10-es tábla után jöhet a 3-as és a 4-es. A szorzótábla gyakorló a szinteket külön kínálja, így a gyerek olyan ütemben haladhat, ahogy az iskolában is tanulják. Hétköznapi helyzetekben (bolt, óra, mérés) a gyerek sokat gyakorol anélkül, hogy észrevenné.",
    faq=[("Mikor tanulják a szorzótáblát másodikban?", "A szorzás bevezetése általában a második osztályban történik, és kezdetben a 2-es, 5-ös és 10-es táblát tanulják. A teljes szorzótábla többnyire harmadikra áll össze, de ez iskolánként eltérhet."),
         ("Mit jelent a tízesátlépés?", "Az olyan összeadás vagy kivonás, ahol az egyesek átlépik a tízes határt, például 8 + 5 vagy 13 − 6. A gyerekek először 10-re egészítik ki a számot, aztán számolnak tovább."),]),
3: dict(
    intro="Harmadikban a számkör 1000-ig bővül, és a szorzótábla teljessé válik. Megjelenik az írásbeli összeadás és kivonás, a maradékos osztás, a törtek első fogalma, és a gyerekek az órát már percre pontosan olvassák. Sok szülő szerint ez az első év, amikor a matek igazán komolyra fordul, ezért itt különösen sokat számít a rendszeres gyakorlás.",
    learn=["számok 1000-ig, kerekítés tízesre és százasra",
           "a teljes szorzótábla és az osztás, maradékos osztás",
           "írásbeli összeadás és kivonás",
           "törtek: fele, harmada, negyede, törtrész felismerése ábráról",
           "római számok olvasása",
           "az óra percre pontosan, mértékegységek átváltása, a kerület és a terület kezdetei"],
    tips="Harmadikban a leggyakoribb nehézség a szorzótábla bizonytalansága, amely később az osztást és a törteket is megnehezíti. Érdemes külön gyakorolni azt az öt-hat szorzatot, amit a gyerek mindig elront. A „Hibáim gyakorlása” gomb pontosan ezt teszi: a rosszul megoldott feladatokból állít össze új kört.",
    faq=[("Mit kell tudnia egy harmadikosnak szorzótáblából?", "A tantervek harmadik osztály végére általában a teljes 10-es szorzótáblát várják, a szorzatokat gyors, biztos felidézéssel, az osztással együtt. A pontos elvárásokat a tanító adja meg."),
         ("Mi az a maradékos osztás?", "Az az osztás, amelynél az osztandó nem osztható maradék nélkül az osztóval, például 23 : 4 = 5, maradék 3. A maradék mindig kisebb, mint az osztó."),]),
4: dict(
    intro="Negyedikben a gyerekek az alsó tagozat utolsó évét járják: a számok 10 000-ig, majd tovább bővülnek, az írásbeli szorzás és osztás is előkerül, és (tankönyvtől függően) megjelennek a tizedes törtek. Ez az év alapozza meg az ötödikes felső tagozatot, ezért érdemes a hiányosságokat most pótolni. A gyakorlók az egész évi anyagot lefedik, nyomtatható munkalappal is.",
    learn=["számok 10 000-ig és tovább, kerekítés tízesre, százasra és ezresre",
           "írásbeli szorzás és osztás egy- és kétjegyű számokkal",
           "törtek összehasonlítása, összeadás és kivonás azonos nevezővel",
           "tizedes törtek: olvasás, írás, összehasonlítás",
           "mértékegységek átváltása, kerület és terület",
           "római számok, számsorozatok, szöveges feladatok"],
    tips="Negyedikben a szöveges feladatok és az írásbeli műveletek jelentik a legnagyobb kihívást. A feladatot érdemes elolvasni, aztán saját szavakkal elmondani, mit kérdez. A munkalap funkcióval ugyanazt a feladatsort ki lehet nyomtatni, és ceruzával, füzetben is lehet számolni, aztán a gyakorlóban ellenőrizni.",
    faq=[("Mit tanul a negyedikes matekból?", "Jellemzően a nagyobb számkört, az írásbeli szorzást és osztást, a törteket, a tizedes törtek kezdeteit, a mértékegységeket, a kerületet és a területet. A tankönyvek tartalma eltérhet."),
         ("Hogyan készüljön a gyerek az ötödik osztályra?", "Érdemes a szorzótáblát, az írásbeli műveleteket és a törtek alapjait megerősíteni, mert az ötödikes anyag ezekre épül. Rövid, napi gyakorlás a legjobb módszer."),]),
5: dict(
    intro="Ötödikben a gyerekek felső tagozatba lépnek: a matek hirtelen elvontabb lesz, megjelennek a negatív számok, a tizedes törtek műveletei, az oszthatóság és a szögek. Sok gyereknek ez az átállás nehéz, mert több lett az új fogalom és kevesebb az ismétlés. Az itt található gyakorlók az év fontos témáit fedik le, a legkönnyebb lépésektől a nehezebbekig.",
    learn=["egész számok és negatív számok, számegyenes, abszolút érték",
           "tizedes törtek összeadása, kivonása, szorzása és osztása",
           "oszthatóság, prímszámok, legnagyobb közös osztó és legkisebb közös többszörös",
           "törtek bővítése és egyszerűsítése",
           "szögek fajtái, háromszög szögei",
           "kerület, terület, mértékegységek"],
    tips="Ötödikben jó szokás, ha a gyerek kisebb tételekre bontva tanul: egy nap egy téma, tíz-tizenöt percben. Ha egy téma nem megy, nem érdemes halogatni, mert a következő tananyag arra épül. A negatív számok és az oszthatóság külön gyakorlóban szerepel, szintenként nehezedő feladatokkal.",
    faq=[("Mit tanul az ötödikes matekból?", "Általában egész számokat, törteket és tizedes törteket, oszthatóságot, szögeket és a kerület-terület számítását. A tananyag tankönyvenként változhat."),
         ("Miért nehéz az ötödik osztályos matek?", "Mert az alsó tagozathoz képest több az absztrakt fogalom, és a tanulóktól nagyobb önállóságot várnak. A rendszeres, rövid gyakorlás sokat segít."),]),
6: dict(
    intro="Hatodikban a törtek és a tizedes törtek műveletei, a százalékszámítás kezdete, a negatív számokkal való számolás és a kör kerülete és területe kerülnek előtérbe. A hatodikos matek sok gyereknek azért nehéz, mert több témát kell párhuzamosan tartani. A gyakorlók évfolyamra szabott szinteken haladnak, a nyomtatható munkalap pedig a dolgozat előtti ismétlést segíti.",
    learn=["törtek: bővítés, egyszerűsítés, közös nevező, összeadás és kivonás",
           "tizedes törtek és az átváltás törtté",
           "negatív számok és a négy alapművelet velük",
           "százalékszámítás alapjai",
           "kör kerülete és területe, a kocka és a téglatest",
           "szöveges feladatok, egyenletek kezdetei"],
    tips="Hatodikban a legtöbb hiba apró számolási tévedésből ered: elfelejtett előjel, rosszul bővített tört. Érdemes a hibákat külön tanulni: a gyakorló a rossz válaszokat elmenti, és a „Hibáim gyakorlása” körben újra elővezeti őket. Dolgozat előtt egy-két munkalap kinyomtatva jó próbaanyag.",
    faq=[("Mikor kezdődik a százalékszámítás?", "A százalék fogalma általában hatodikban jelenik meg, a részletesebb számítás hetedikben és nyolcadikban. Az iskolák tantervei eltérhetnek."),
         ("Hogyan lehet gyakorolni a törteket?", "Érdemes az ábrázolástól indulni (pizza, szakasz), aztán a bővítésre, egyszerűsítésre, végül az összeadásra és kivonásra áttérni. A törtek haladó gyakorlója ebben a sorrendben vezet végig."),]),
7: dict(
    intro="Hetedikben a matek a számolásból egyre inkább az algebra felé tolódik: egyenletek, hatványok, százalékszámítás és a geometria összefüggései kerülnek középpontba. Ezen a szinten már számít a rutin: aki gyorsan és biztosan számol, az a nehezebb feladatokra is több figyelmet tud fordítani. Az itt található gyakorlók az egyenletektől a négyzetgyökig lefedik az év fontos témáit.",
    learn=["egyenletek megoldása a mérlegelvvel, szöveges egyenletek",
           "százalékszámítás: kedvezmény, árváltozás, az alap meghatározása",
           "hatványozás és négyzetgyök",
           "törtek és negatív számok biztos kezelése",
           "háromszögek és négyszögek szögei, sokszögek belső szögei",
           "oszthatóság, prímtényezős felbontás"],
    tips="Hetedikben az a leghasznosabb, ha a gyerek a lépéseket leírja, és nem fejben oldja meg az egyenleteket. A gyakorló magyarázata mutatja a lépéseket, de a füzet használata is fontos. A munkalap funkcióval kinyomtatott feladatsor jó ismétlés a témazáró előtt.",
    faq=[("Mit tanul a hetedikes matekból?", "Jellemzően egyenleteket, százalékszámítást, hatványokat, négyzetgyököt és háromszögekhez kapcsolódó geometriát. A pontos anyag tankönyvenként változik."),
         ("Hogyan gyakorolhatja a gyerek az egyenleteket?", "Érdemes az egyszerű, egylépéses egyenletekkel kezdeni, aztán áttérni a kétlépésesekre és a zárójelesekre. Minden megoldás után a behelyettesítés jó ellenőrzés."),]),
8: dict(
    intro="Nyolcadikban az általános iskolai matek lezárul, és sok gyerek a középiskolai felvételire is készül. A százalékszámítás, az egyenletek, a hatványok és gyökök, a kör és a testek felszíne és térfogata mind visszatérő felvételi témák. Az itt található gyakorlók ezekre az alapokra épülnek, így az ismétlés és a hiányok pótlása egyaránt jól megy velük.",
    learn=["egyenletek és szöveges feladatok biztos megoldása",
           "százalékszámítás: kedvezmény, áremelés, az alap meghatározása",
           "hatványok, négyzetgyök, kitevő keresése",
           "kör kerülete és területe, kocka és téglatest felszíne és térfogata",
           "szögek és háromszögek tulajdonságai",
           "számelmélet: prímek, LNKO, LKKT"],
    tips="Nyolcadikban érdemes a hiányokat célzottan keresni: ha egy témában gyakran hibázik a gyerek, azt külön szinten érdemes gyakorolni. A munkalapok kinyomtatva a felvételi előtti időszakban jó próbafeladatok. Az időre menő mód a gyorsaságot fejleszti, és a nyomás kezelését is gyakorolja.",
    faq=[("Mit érdemes ismételni a felvételi előtt?", "A felvételi feladatsorokban gyakran szerepelnek egyenletek, százalékszámítás, geometriai számítások és szöveges feladatok. A szaktanár vagy az iskola tájékoztatása a pontos követelményeket mutatja."),
         ("Hogyan lehet gyorsítani a számolást?", "A szorzótábla, az előjelszabályok és a törtek alapműveletei automatizálása a legtöbbet segít. Ehhez rövid, napi ismétlés vagy az időre menő mód használható."),]),
}

# Helyesírás és nyelvtan: évfolyamonként
NYELV = {
1: dict(
    intro="Az első osztályban a gyerekek a betűkkel és a hangokkal ismerkednek: megtanulnak olvasni és írni, szótagolni, és az első helyesírási szabályokkal találkoznak. A hosszú és rövid magánhangzók helyes jelölése az egyik első fontos téma, mert a magyarban a hosszúság megváltoztathatja a szó jelentését (például kor – kór, ver – vér). A gyakorló rövid, játékos feladatokkal segít a begyakorlásban.",
    learn=["hangok és betűk, a magyar ábécé sorrendje",
           "szótagolás, a szó szótagjainak számolása",
           "hosszú és rövid magánhangzók: i – í, u – ú, ö – ő, ü – ű, e – é, o – ó, a – á",
           "mondatkezdő nagybetű, mondatvégi írásjel",
           "szavak olvasása és másolása"],
    tips="Elsősnek a szóbeli gyakorlás sokat segít: mondjátok ki hangosan a szót, és figyeljétek meg, melyik magánhangzó hosszú. A gyakorlóban a feladatok rövidek, tíz kérdésből állnak. Ha a gyerek még nem olvas folyékonyan, olvasd fel neki a szót, és együtt keressétek meg a helyes alakot.",
    faq=[("Mikor tanulják a hosszú és rövid magánhangzókat?", "Az olvasás-írás tanulásával együtt, az első osztály során. A helyesírás gyakorlása aztán végigkíséri az alsó tagozatot."),
         ("Hogyan számoljuk a szótagokat?", "A magyarban minden magánhangzó egy szótagot ad, ezért elég megszámolni a szó magánhangzóit. Például a „csillag” két szótagú (csil-lag), a „repülőgép” négy (re-pü-lő-gép)."),]),
2: dict(
    intro="Másodikban a helyesírás egyik legismertebb nehézsége, a j és ly megkülönböztetése jelenik meg először. A gyerekek a mondatfajtákat is megismerik, és tovább gyakorolják a hosszú és rövid magánhangzókat, a szótagolást és az ábécé-sorrendet. Az itt található gyakorlók rövid, játékos feladatokkal vezetnek végig ezeken a témákon.",
    learn=["j vagy ly: a leggyakoribb szavak megtanulása",
           "hosszú és rövid magánhangzók",
           "kijelentő, kérdő és felkiáltó mondatok",
           "szótagolás, elválasztás, ábécé-sorrend",
           "szavak és mondatok másolása, diktálás"],
    tips="A j és az ly szavanként tanulható. Hasznos, ha a gyerek a gyakori ly-os szavakat külön listába gyűjti (hely, folyó, király, golyó), mert az ly-os szavak kevesebben vannak, mint a j-sek. Rövid, napi gyakorlás többet ér, mint egy hosszú hétvégi tanulás.",
    faq=[("Hogyan tanulja meg a gyerek a j és az ly helyesírását?", "Szavanként, ismétléssel. Az ly-os szavak kisebb csoportot alkotnak, ezért érdemes azokat külön megtanulni, a többi szó nagy részét pedig j-vel írjuk. A gyakorló gyakori szavakkal dolgozik."),
         ("Mik a mondatfajták?", "A mondat célja szerint lehet kijelentő, kérdő, felkiáltó, felszólító és óhajtó. Az első években általában a kijelentő, kérdő és felkiáltó mondattal ismerkednek, a pontos sorrend iskolánként eltérhet."),]),
3: dict(
    intro="Harmadikban a helyesírás-gyakorlás mellé a nyelvtan is belép: a gyerekek megismerik a szófajokat, a toldalékokat és a mondatfajták pontos rendszerét. A -val és -vel rag hasonulása, a j és ly szavai és a szófajok felismerése sok hibalehetőséget rejt, ezért itt a legfontosabb a rendszeres gyakorlás. Az alábbi gyakorlók mindhárom területet lefedik.",
    learn=["j vagy ly: a gyakori szavak megerősítése",
           "szófajok: főnév, melléknév, ige, számnév",
           "mondatfajták: kijelentő, kérdő, felkiáltó, felszólító, óhajtó",
           "toldalékok: a -val és -vel rag hasonulása (kézzel, tollal)",
           "szótagolás, ábécé-sorrend szavakkal"],
    tips="A szófajok felismerésében segít a kérdezés: a főnév „ki? mi?”, a melléknév „milyen?”, az ige „mit csinál?”. Érdemes a gyerekkel együtt kitalálni néhány mondatot, aztán megkeresni bennük a szófajokat. A rövid gyakorló körök ezt játékossá teszik.",
    faq=[("Mik a szófajok, amiket harmadikban tanulnak?", "Általában a főnevet, a melléknevet, az igét és a számnevet. A kérdések: ki? mi? (főnév), milyen? (melléknév), mit csinál? (ige), hány? (számnév)."),
         ("Hogyan írjuk a -val, -vel ragot?", "Magánhangzó után a v megmarad (tűvel, almával). Mássalhangzó után hasonul: kéz + vel = kézzel, toll + val = tollal. A magánhangzót a szó utolsó magánhangzója szabja meg: mély (-val) vagy magas (-vel)."),]),
4: dict(
    intro="Negyedikben a helyesírási és nyelvtani ismeretek összeállnak: a j és ly, a szófajok, a mondatfajták és a toldalékok mind visszatérnek, magasabb szinten. Ez az utolsó alsós év, ezért sok iskola év végi felmérésen is ellenőrzi ezeket. A gyakorlók az év egész anyagát lefedik, rövid körökben.",
    learn=["j és ly: bővülő szólista, szócsaládok",
           "szófajok felismerése, a főnév, melléknév, ige, számnév megkülönböztetése",
           "mondatfajták és a mondatvégi írásjelek",
           "toldalékok helyesírása",
           "hosszú és rövid magánhangzók"],
    tips="Negyedikben a gyerekek már önállóbban dolgoznak, de a diktálás és a másolás továbbra is fontos. Ha egy gyakori hiba visszatér, érdemes külön gyakorolni: a gyakorló a rossz válaszokat elmenti, és a „Hibáim gyakorlása” körben újra elővezeti őket.",
    faq=[("Mit kell tudnia a negyedikesnek helyesírásból?", "A tanterv szerint a gyakori szavak helyesírását (j-ly, hosszú-rövid hangok), a toldalékos alakokat és a mondatfajták jelölését. A pontos elvárásokat az iskola adja meg."),
         ("Hogyan készüljön a gyerek az ötödik osztályra?", "A j-ly szavak ismétlése, a szófajok felismerése és a toldalékok helyes használata a legfontosabb. Napi 10 perc gyakorlás elég."),]),
5: dict(
    intro="Ötödikben a nyelvtan és a helyesírás egyre elvontabb: a szófajok rendszere, a mondatfajták és a toldalékolás mind magasabb szinten ismétlődnek. A j és ly bizonytalansága sok felsősnél még megmarad, ezért érdemes ezt tovább gyakorolni. A gyakorlók ismétlésre és hiányok pótlására egyaránt alkalmasak.",
    learn=["j vagy ly: a nehezebb szavak",
           "szófajok és a szófaji besorolás",
           "mondatfajták, az írásjelek használata",
           "a toldalékok (-val, -vel és más ragok) helyes használata",
           "a szavak szófaji besorolása és elemzése"],
    tips="Ötödikben a nyelvtani fogalmak száma megnő, ezért érdemes a szabályokat példákkal együtt tanulni. A gyakorlóban a legtöbb válasz után rövid magyarázat látszik. Ha a gyerek bizonytalan a j-ly szavakban, érdemes a szócsaládokra figyelni (folyik – folyó – folyosó).",
    faq=[("Miért nehéz a magyar nyelvtan ötödikben?", "Mert több az absztrakt fogalom (szófaj, szerkezet), és a szabályok mellé kivételek is kerülnek. A rendszeres, rövid gyakorlás sokat segít."),
         ("Mit érdemes ötödikben ismételni?", "A j-ly szavakat, a szófajok felismerését és a toldalékolás szabályait. Ha a gyerek ezekben biztos, a többi témát is könnyebben tanulja."),]),
6: dict(
    intro="Hatodikban a nyelvtan a szófajok pontos rendszerére és a toldalékolás szabályaira épül. Ezek a témák a dolgozatokban és a felvételin egyaránt gyakoriak. A hatodikosok már önálló gyakorlásra képesek, a gyakorlók pedig segítik a rutin kialakítását. Itt a szófajok és a toldalékok szintjei találhatók.",
    learn=["szófajok felismerése és csoportosítása",
           "a toldalékok helyes használata és helyesírása",
           "a -val és -vel rag hasonulása",
           "a mondatfajták és az írásjelek ismétlése"],
    tips="Hatodikban érdemes az ismétlést rendszeressé tenni: heti két-három alkalom, tíz-tizenöt percben. A szófajok megkülönböztetésében segít, ha a gyerek megkérdezi a szót (ki? mi? milyen? mit csinál?), és a toldalékoknál a szó végére figyel.",
    faq=[("Mit tanulnak hatodikban magyar nyelvtanból?", "Jellemzően a szófajok rendszerét, a toldalékolást és a mondatok elemzését. A tananyag tankönyvenként eltérhet."),
         ("Mire jó a gyakorló hatodikban?", "A hiányok pótlására és az ismétlésre. A rövid körök gyors visszajelzést adnak, és a hibák külön gyakorolhatók."),]),
}

# ---- Környezetismeret (1–4. osztály) és természetismeret (5–6. osztály) ----
TERM = {
 1: {'intro': 'Az első osztályban a környezetismeret a gyerek közvetlen környezetével ismerteti meg: az évszakokkal, a hét napjaival és a hónapokkal, a testünkkel és az érzékszerveinkkel, a háziállatokkal és a növényekkel. Az itt található gyakorlók rövid, játékos kérdésekkel segítenek ezeken a témákon.',
     'learn': ['a hét napjai, a hónapok és az évszakok sorrendje', 'az évszakok jellemzői, az időjárás', 'a testünk részei és az érzékszerveink (szem, fül, orr, nyelv, bőr)', 'háziállatok és vadon élő állatok, kicsinyeik és hangjuk', 'gyümölcsök, zöldségek, fák és virágok megismerése'],
     'tips': 'Elsősnek a séta és a megfigyelés a legjobb tanító. Mutassatok rá az évszakok jeleire, nevezzétek meg közösen az állatokat és a növényeket, és utána a gyakorlóval játékosan felelevenítheti, amit látott. Napi 5–10 perc elég.',
     'faq': [('Mit tanul a gyerek környezetismeretből első osztályban?', 'Az első osztályban a közvetlen környezettel ismerkedik: az évszakokkal, a napokkal és hónapokkal, a testével, az érzékszervekkel, az állatokkal és a növényekkel. A pontos tananyag iskolánként eltérhet.'), ('Hogyan gyakoroltassam otthon a környezetismeretet?', 'Beszélgessetek a megfigyeléseiről séta közben, és használjátok a rövid kvízfeladatokat. A gyerek így játékosan ismétli át az évszakokat, az állatokat és a növényeket.')]},
 2: {'intro': 'Másodikban a gyerekek tovább mélyítik a természet megismerését: az évszakok és az időjárás kapcsolatát, az állatok élőhelyét és táplálkozását, a növényeket, valamint az egészséges életmód alapjait tanulják. A gyakorlók ezeket a témákat veszik végig rövid kérdésekkel.',
     'learn': ['az évszakok, a hónapok hossza és az ünnepek', 'az időjárás elemei és az öltözködés az időjáráshoz', 'állatok élőhelye, táplálkozása, kicsinyei', 'gyümölcsök, zöldségek, fák és bokrok', 'az egészséges életmód: mozgás, étkezés, alvás, tisztálkodás'],
     'tips': 'Másodikosnál működik, ha a tanultakat a mindennapokhoz kötjük: reggel megnézitek az időjárást, kiválasztjátok a megfelelő ruhát, és megbeszélitek, mit esznek az állatok. Rövid, rendszeres gyakorlás többet ér, mint az egyszeri hosszú tanulás.',
     'faq': [('Mi az időjárás és hogyan mérjük?', 'Az időjárás a levegő pillanatnyi állapota: hőmérséklet, csapadék, szél és felhőzet. A hőmérsékletet hőmérővel, a csapadék mennyiségét esőmérővel mérjük.'), ('Miben segít a gyakorló?', 'Rövid kérdésekkel gyakoroltatja az állatok, növények, évszakok és az emberi test alapjait, így a gyerek játékosan ismétli át a tananyagot.')]},
 3: {'intro': 'Harmadik osztályban a gyerekek már rendszerezik a természet jelenségeit: az anyagokat és tulajdonságaikat, a víz állapotait, az időjárást és a víz körforgását, az állatok csoportjait és az emberi testet. A gyakorlók a legfontosabb fogalmakat gyakoroltatják.',
     'learn': ['szilárd, folyékony és légnemű anyagok', 'a víz körforgása, a csapadék fajtái', 'állatcsoportok: emlősök, madarak, halak, hüllők, kétéltűek, rovarok', 'a növények részei és feladatuk', 'a szervek és az érzékszervek feladata'],
     'tips': 'Egyszerű kísérletekkel érdemes megerősíteni a tanultakat: tegyetek jeget a meleg szobába, figyeljétek meg, mi úszik és mi merül el a vízben, és használjatok mágnest. Utána a gyakorlóval ellenőrizhető, mi maradt meg.',
     'faq': [('Mik a halmazállapotok?', 'Az anyagok lehetnek szilárdak (például kő, fa), folyékonyak (például víz, olaj) és légneműek (például levegő). A víz mindhárom állapotban előfordul: jég, víz és vízgőz.'), ('Hogyan készüljön a gyerek egy környezetismeret-felelésre?', 'Érdemes a fogalmakat saját szavaival elmondatni, példákat gyűjteni, és rövid kvízekkel ellenőrizni a tudását.')]},
 4: {'intro': 'Negyedikben a környezetismeret az életközösségek és az anyagok világa felé nyit: a gyerekek megismerik az élőhelyeket, a táplálékláncok alapjait, az anyagok tulajdonságait, valamint az emberi test működését. A gyakorlók ezeket az összefüggéseket gyakoroltatják.',
     'learn': ['élőhelyek: erdő, rét, tó, tenger, sivatag', 'egyszerű táplálékláncok', 'az anyagok tulajdonságai: mágnesesség, oldódás, úszás', 'halmazállapot-változások', 'a szervrendszerek és az egészséges életmód'],
     'tips': 'Negyedikben nagy segítség, ha a gyerek maga rajzol táplálékláncot, vagy gyűjti, melyik állat hol él. Ez segít megérteni az összefüggéseket, nem csak bemagolni a szavakat.',
     'faq': [('Mi az a tápláléklánc?', 'A tápláléklánc megmutatja, ki kit eszik meg. Az elején mindig a növény áll, mert ő maga készíti a táplálékát, utána jönnek az állatok, például fű, nyúl, róka.'), ('Mit jelent a halmazállapot-változás?', 'Például az olvadás (szilárdból folyékony), a fagyás (folyékonyból szilárd), a párolgás (folyékonyból légnemű) és a lecsapódás (légneműből folyékony).')]},
 5: {'intro': 'Ötödik osztálytól a tantárgy neve természetismeret. A gyerekek az élő és élettelen természet kapcsolatait vizsgálják: az anyagok halmazállapotát, a vizet és a levegőt, az élőhelyeket, valamint a növények, állatok és az emberi test működését. A gyakorlók ehhez adnak gyors ismétlési lehetőséget.',
     'learn': ['az anyagok halmazállapota és változásai, a víz fagyás- és forráspontja', 'az időjárás elemei és a víz körforgása', 'élőhelyek és táplálékláncok', 'a növények és állatok életműködése, állatcsoportok', 'az emberi test szervrendszerei'],
     'tips': 'A természetismeretnél a fogalmak értése többet számít, mint a magolás. Kérd meg a gyereket, hogy a saját szavaival magyarázza el, például hogyan működik a víz körforgása, és ezután gyakorolja a pontos kifejezéseket kvízkérdésekkel.',
     'faq': [('Miért természetismeret az ötödik osztályos tantárgy neve?', 'Ötödiktől a környezetismeretet a természetismeret váltja fel, amely részletesebben foglalkozik az élő és élettelen természettel. A pontos tananyag tankönyvenként eltérhet.'), ('Hogyan tanulhatja meg a gyerek a szervrendszereket?', 'Érdemes szervrendszerenként gyűjteni a szerveket (például légzőrendszer: orr, gége, légcső, tüdő), és ábrával, rövid kvízekkel ismételni.')]},
 6: {'intro': 'Hatodikban a természetismeret az élő természet összefüggéseit és az emberi testet tekinti át részletesebben. A gyakorlók a szervrendszereket, az élőhelyeket, a táplálékláncokat, valamint a termelők, fogyasztók és lebontók szerepét gyakoroltatják.',
     'learn': ['a szervrendszerek: légzés, keringés, emésztés, mozgás, idegrendszer, kiválasztás', 'élőhelyek és életközösségek', 'termelők, fogyasztók és lebontók', 'növények: a részek feladata, fák, lomb- és tűlevelűek', 'anyagok és halmazállapotok'],
     'tips': 'Hatodikban sok az új szó. Segít egy saját szószedet, ahová a gyerek példával írja fel a fogalmakat (például termelő: fű). A gyakorlóval hetente érdemes átismételni a leggyengébb témákat.',
     'faq': [('Mik a termelők, fogyasztók és lebontók?', 'A termelők a napfényből maguk készítik a táplálékukat (a növények). A fogyasztók másokat esznek meg (az állatok), a lebontók, például a gombák és a baktériumok, az elhalt anyagot bontják le.'), ('Hány szervrendszert tanulnak hatodikban?', 'Általában a légző-, keringési, emésztő-, mozgás-, ideg- és kiválasztó rendszert, de ez tankönyvenként eltérhet.')]},
}
